language: php
php:
  - 7.3
services:
  - mysql 
cache:
  directories:
    - vendor
before_script:
  - mysql -e 'CREATE DATABASE patricia;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
script:
  - vendor/bin/phpunit

